# Minimal Home Assistant configuration for CronoStar

default_config:

automation: !include_dir_merge_list automations
homeassistant:
  packages: !include_dir_named packages


lovelace:
  mode: yaml
  resources:
    - url: /local/cronostar_card/cronostar-card.js
      type: module

# Enable the CronoStar backend
cronostar:
