# Minimal Home Assistant configuration for CronoStar

default_config:

# Enable the CronoStar integration
#cronostar:

lovelace:
  mode: yaml
  resources:
    - url: /cronostar_card/cronostar-card.js
      type: module